# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/orange/Documents/College/CST-310/GraphicsDevelopment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/orange/Documents/College/CST-310/GraphicsDevelopment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/orange/Documents/College/CST-310/GraphicsDevelopment/CMakeFiles /home/orange/Documents/College/CST-310/GraphicsDevelopment//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/orange/Documents/College/CST-310/GraphicsDevelopment/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GraphicsOpenGL

# Build rule for target.
GraphicsOpenGL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GraphicsOpenGL
.PHONY : GraphicsOpenGL

# fast build rule for target.
GraphicsOpenGL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/build
.PHONY : GraphicsOpenGL/fast

src/DisplayObject.o: src/DisplayObject.cpp.o
.PHONY : src/DisplayObject.o

# target to build an object file
src/DisplayObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/DisplayObject.cpp.o
.PHONY : src/DisplayObject.cpp.o

src/DisplayObject.i: src/DisplayObject.cpp.i
.PHONY : src/DisplayObject.i

# target to preprocess a source file
src/DisplayObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/DisplayObject.cpp.i
.PHONY : src/DisplayObject.cpp.i

src/DisplayObject.s: src/DisplayObject.cpp.s
.PHONY : src/DisplayObject.s

# target to generate assembly for a file
src/DisplayObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/DisplayObject.cpp.s
.PHONY : src/DisplayObject.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/WindowManager.o: src/WindowManager.cpp.o
.PHONY : src/WindowManager.o

# target to build an object file
src/WindowManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/WindowManager.cpp.o
.PHONY : src/WindowManager.cpp.o

src/WindowManager.i: src/WindowManager.cpp.i
.PHONY : src/WindowManager.i

# target to preprocess a source file
src/WindowManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/WindowManager.cpp.i
.PHONY : src/WindowManager.cpp.i

src/WindowManager.s: src/WindowManager.cpp.s
.PHONY : src/WindowManager.s

# target to generate assembly for a file
src/WindowManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/WindowManager.cpp.s
.PHONY : src/WindowManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicsOpenGL.dir/build.make CMakeFiles/GraphicsOpenGL.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GraphicsOpenGL"
	@echo "... src/DisplayObject.o"
	@echo "... src/DisplayObject.i"
	@echo "... src/DisplayObject.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/WindowManager.o"
	@echo "... src/WindowManager.i"
	@echo "... src/WindowManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

